export const TYPES = {
    Logger: Symbol.for('Logger'),
    WorkspaceManager: Symbol.for('WorkspaceManager'),
    GherkinParser: Symbol.for('GherkinParser'),
    TsParser: Symbol.for('TsParser'),
    MatchEngine: Symbol.for('MatchEngine'),
    McpBridge: Symbol.for('McpBridge'),
    PlaywrightBddAdapter: Symbol.for('PlaywrightBddAdapter'),
    CucumberAdapter: Symbol.for('CucumberAdapter'),
    AiController: Symbol.for('AiController'),
    TestController: Symbol.for('TestController'),
    NavigationProvider: Symbol.for('NavigationProvider'),
    ExecutionService: Symbol.for('ExecutionService'),
    AiSidebar: Symbol.for('AiSidebar'),
    CompletionProvider: Symbol.for('CompletionProvider'),
    LLMProvider: Symbol.for('LLMProvider'),
    AnthropicProvider: Symbol.for('AnthropicProvider'),
    Onboarding: Symbol.for('Onboarding'),
    UserStore: Symbol.for('UserStore'),
    UserStoreProvider: Symbol.for('UserStoreProvider'),
    FormattingProvider: Symbol.for('FormattingProvider'),
    StepGenerationCodeLensProvider: Symbol.for('StepGenerationCodeLensProvider'),
    TestStateStore: Symbol.for('TestStateStore'),
    AutoHealCodeLensProvider: Symbol.for('AutoHealCodeLensProvider'),
    ExecutionCodeLensProvider: Symbol.for('ExecutionCodeLensProvider'),
};
